CREATE TABLE IF NOT EXISTS shops (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, seller_id BIGINT NOT NULL UNIQUE, name VARCHAR(80) NOT NULL,
 announcement VARCHAR(500) NOT NULL DEFAULT '', status VARCHAR(20) NOT NULL DEFAULT 'OPEN',
 decoration_template VARCHAR(20) NOT NULL DEFAULT 'CLASSIC', decoration_json TEXT NOT NULL,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
