export const MSG_TYPE_BARGAIN_APPLY = "MSG_TYPE_BARGAIN_APPLY";
export const MSG_TYPE_BARGAIN_CONFIRM = "MSG_TYPE_BARGAIN_CONFIRM";
export const MSG_TYPE_AUCTION_OUTBID = "MSG_TYPE_AUCTION_OUTBID";
export const MSG_TYPE_AUCTION_BID_ACCEPTED = "MSG_TYPE_AUCTION_BID_ACCEPTED";
export const MSG_TYPE_AUCTION_SETTLED = "MSG_TYPE_AUCTION_SETTLED";
