{{- if .Values.messaging.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: messaging
  labels:
    {{- include "segroup8.labels" . | nindent 4 }}
    app.kubernetes.io/component: messaging
spec:
  selector:
    {{- include "segroup8.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: messaging
  ports:
    - name: http
      port: 8084
      targetPort: http
{{- end }}
