apiVersion: v1
kind: ConfigMap
metadata:
  name: segroup8-mysql-init
  labels:
    {{- include "segroup8.labels" . | nindent 4 }}
data:
  01-schema.sql: |-
    {{- required "mysql.initSchema must be supplied with --set-file" .Values.mysql.initSchema | nindent 4 }}
