{{- if .Values.secondhand.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: secondhand-service
  labels:
    {{- include "segroup8.labels" . | nindent 4 }}
    app.kubernetes.io/component: secondhand-service
spec:
  type: ClusterIP
  selector:
    {{- include "segroup8.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: secondhand-service
  ports:
    - name: http
      port: {{ .Values.secondhand.service.port }}
      targetPort: http
{{- end }}
