apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: segroup8-uploads
  labels:
    {{- include "segroup8.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.backend.uploads.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.backend.uploads.size }}
