classDiagram
    class VoucherController
    class VoucherService
    class VoucherSaveRequest
    class Voucher
    class VoucherVO
    VoucherController --> VoucherService
    VoucherController --> VoucherSaveRequest
    VoucherService --> Voucher
    VoucherService --> VoucherVO
