%% CONCEPT-CLASS01
classDiagram
  class User {
    +identifier: String
    +state: String
  }
  class Credential {
    +identifier: String
    +state: String
  }
  class Role {
    +identifier: String
    +state: String
  }
  User "1" --> "0..*" Credential : 关联
  Credential "0..*" --> "1" Role : 产生/归属
