package com.segroup8.catalogshop;

import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.doThrow;
import static org.mockito.Mockito.reset;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

import com.segroup8.security.JwtPrincipal;
import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.security.Keys;
import java.nio.charset.StandardCharsets;
import java.util.Date;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.web.servlet.MockMvc;

@SpringBootTest @AutoConfigureMockMvc @Tag("DOMAIN_B")
class CatalogShopApiTest {
    private static final String SECRET="SEGROUP8_TEST_SECRET_MUST_BE_AT_LEAST_32_BYTES_LONG";
    @Autowired MockMvc mvc;@Autowired JdbcTemplate db;@Autowired InventoryModule inventory;
    @MockBean IdentityAccessVerifier access;
    @BeforeEach void seed(){reset(access);for(String table:new String[]{"outbox_event","idempotency_record","inventory_reservation_item","inventory_reservation","product_risk_audit","browse_history","user_search_history","search_keyword_stat","product","shop","category"})db.update("delete from "+table);db.update("insert into category(id,parent_id,name,sort_order,active) values(1,null,'图书',1,true)");db.update("insert into shop(id,seller_id,merchant_application_id,name,status,decoration_template,decoration_json) values(10,7,'app-1','测试店','OPEN','CLASSIC','{}')");db.update("insert into product(id,seller_id,shop_id,category_id,name,description,price,stock,reserved_stock,status) values(100,7,10,1,'Java 图书','微服务',59,10,0,'ON_SALE')");}
    @Test @Tag("UC06") void publicCatalogHasStableEnvelopeAndDistinctRoutes()throws Exception{mvc.perform(get("/api/category/tree")).andExpect(status().isOk()).andExpect(jsonPath("$.data[0].name").value("图书"));mvc.perform(get("/api/product/list").param("shopId","10")).andExpect(status().isOk()).andExpect(jsonPath("$.data.records[0].id").value(100));mvc.perform(get("/api/product/search").param("keyword","java")).andExpect(status().isOk()).andExpect(jsonPath("$.data.records[0].id").value(100));mvc.perform(get("/api/product/detail/100")).andExpect(status().isOk()).andExpect(jsonPath("$.data.stock").value(10));}
    @Test void rejectsAnonymousWrongRoleForgedHeaderAndInactiveAccount()throws Exception{mvc.perform(get("/api/product/seller/list")).andExpect(status().isUnauthorized());mvc.perform(get("/api/admin/product-risk-audits").header("Authorization",bearer(2,"USER"))).andExpect(status().isForbidden());mvc.perform(get("/api/product/seller/list").header("Authorization",bearer(7,"OFFICIAL_SELLER")).header("X-Seller-Id","999")).andExpect(status().isOk()).andExpect(jsonPath("$.data.records[0].sellerId").value(7));doThrow(new ApiException("ACCOUNT_INACTIVE","用户已封禁",HttpStatus.UNAUTHORIZED)).when(access).requireActive(any(),any(JwtPrincipal.class));mvc.perform(get("/api/user/browse-history").header("Authorization",bearer(2,"USER"))).andExpect(status().isUnauthorized()).andExpect(jsonPath("$.error").value("ACCOUNT_INACTIVE"));}
    @Test @Tag("UC07") void sellerLifecycleUsesJwtIdentity()throws Exception{String body="{\"shopId\":10,\"categoryId\":1,\"name\":\"新书\",\"description\":\"正常商品\",\"price\":20,\"stock\":3,\"cover\":\"/uploads/book.png\",\"images\":[\"/uploads/book.png\"]}";mvc.perform(post("/api/product/seller").header("Authorization",bearer(7,"OFFICIAL_SELLER")).contentType(MediaType.APPLICATION_JSON).content(body)).andExpect(status().isCreated()).andExpect(jsonPath("$.data.status").value(1)).andExpect(jsonPath("$.data.cover").value("/uploads/book.png")).andExpect(jsonPath("$.data.images[0]").value("/uploads/book.png"));mvc.perform(put("/api/product/seller/100").header("Authorization",bearer(8,"OFFICIAL_SELLER")).contentType(MediaType.APPLICATION_JSON).content(body)).andExpect(status().isNotFound());mvc.perform(post("/api/product/seller/100/stock/adjust").header("Authorization",bearer(7,"OFFICIAL_SELLER")).contentType(MediaType.APPLICATION_JSON).content("{\"delta\":4}")).andExpect(status().isOk()).andExpect(jsonPath("$.data.stock").value(14));}
    @Test @Tag("UC08") void shopUsesJwtAndSupportsFrontendRoute()throws Exception{mvc.perform(put("/api/shop/seller/decoration").header("Authorization",bearer(7,"OFFICIAL_SELLER")).contentType(MediaType.APPLICATION_JSON).content("{\"decorationJson\":\"{}\"}")).andExpect(status().isOk()).andExpect(jsonPath("$.data.decorationTemplate").value("GRID"));mvc.perform(put("/api/shop/seller/decoration").header("Authorization",bearer(2,"USER")).contentType(MediaType.APPLICATION_JSON).content("{\"decorationJson\":\"{}\"}")).andExpect(status().isForbidden());}
    @Test @Tag("UC09") void riskDetailAndDecisionRequireAdmin()throws Exception{String body="{\"shopId\":10,\"categoryId\":1,\"name\":\"违禁商品\",\"description\":\"枪支\",\"price\":20,\"stock\":3}";mvc.perform(post("/api/product/seller").header("Authorization",bearer(7,"OFFICIAL_SELLER")).contentType(MediaType.APPLICATION_JSON).content(body)).andExpect(status().isCreated());long audit=db.queryForObject("select max(id) from product_risk_audit",Long.class);mvc.perform(get("/api/admin/product-risk-audits/"+audit).header("Authorization",bearer(1,"ADMIN"))).andExpect(status().isOk()).andExpect(jsonPath("$.data.riskLevel").value("HIGH"));mvc.perform(post("/api/admin/product-risk-audits/"+audit+"/decision").header("Authorization",bearer(1,"ADMIN")).contentType(MediaType.APPLICATION_JSON).content("{\"decision\":\"REJECTED\",\"adminRemark\":\"规则命中\"}")).andExpect(status().isOk()).andExpect(jsonPath("$.data.auditStatus").value("REJECTED"));String payload=db.queryForObject("select payload from outbox_event where event_type='NotificationRequested.v1'",String.class);org.junit.jupiter.api.Assertions.assertTrue(payload.contains("recipientUserId")&&payload.contains("dedupeKey")&&payload.contains("displayTitle")&&payload.contains("displayText"));}
    @Test @Tag("UC10") void behaviorIsJwtScopedAndDeleteByIdExists()throws Exception{mvc.perform(post("/api/user/browse-history").header("Authorization",bearer(2,"USER")).contentType(MediaType.APPLICATION_JSON).content("{\"productId\":100,\"productType\":\"NEW\"}")).andExpect(status().isCreated());long id=db.queryForObject("select id from browse_history where user_id=2",Long.class);mvc.perform(get("/api/user/browse-history").header("Authorization",bearer(3,"USER"))).andExpect(status().isOk()).andExpect(jsonPath("$.data.length()").value(0));mvc.perform(delete("/api/user/browse-history/"+id).header("Authorization",bearer(3,"USER"))).andExpect(status().isNotFound());mvc.perform(delete("/api/user/browse-history/"+id).header("Authorization",bearer(2,"USER"))).andExpect(status().isOk());}
    @Test void authenticatedPublicSearchRecordsHistory()throws Exception{mvc.perform(get("/api/product/list").param("keyword","Java 图书").header("Authorization",bearer(2,"USER"))).andExpect(status().isOk());mvc.perform(get("/api/search/history").header("Authorization",bearer(2,"USER"))).andExpect(status().isOk()).andExpect(jsonPath("$.data[0]").value("Java 图书"));}
    @Test void idempotencyKeyRejectsDifferentRequest()throws Exception{String one="{\"orderId\":\"order-1\",\"items\":[{\"productId\":100,\"quantity\":3}]}";String changed="{\"orderId\":\"order-1\",\"items\":[{\"productId\":100,\"quantity\":2}]}";mvc.perform(post("/internal/inventory/reservations").header("X-Internal-Service-Token","test-token").header("X-Idempotency-Key","idem-1").contentType(MediaType.APPLICATION_JSON).content(one)).andExpect(status().isCreated());mvc.perform(post("/internal/inventory/reservations").header("X-Internal-Service-Token","test-token").header("X-Idempotency-Key","idem-1").contentType(MediaType.APPLICATION_JSON).content(one)).andExpect(status().isCreated());mvc.perform(post("/internal/inventory/reservations").header("X-Internal-Service-Token","test-token").header("X-Idempotency-Key","idem-1").contentType(MediaType.APPLICATION_JSON).content(changed)).andExpect(status().isConflict()).andExpect(jsonPath("$.error").value("IDEMPOTENCY_KEY_CONFLICT"));}
    @Test void concurrentReservationsDoNotOversell()throws Exception{db.update("update product set stock=5 where id=100");var pool=java.util.concurrent.Executors.newFixedThreadPool(2);var start=new java.util.concurrent.CountDownLatch(1);java.util.concurrent.Callable<Boolean> call=()->{start.await();try{inventory.reserve(java.util.UUID.randomUUID().toString(),new InventoryController.ReserveRequest(java.util.UUID.randomUUID().toString(),java.util.List.of(new InventoryController.Item(100,4))));return true;}catch(ApiException e){return false;}};var a=pool.submit(call);var b=pool.submit(call);start.countDown();org.junit.jupiter.api.Assertions.assertEquals(1,(a.get()?1:0)+(b.get()?1:0));pool.shutdownNow();}
    private String bearer(long id,String role){byte[] key=SECRET.getBytes(StandardCharsets.UTF_8);String token=Jwts.builder().subject(String.valueOf(id)).claim("uid",id).claim("username","user"+id).claim("role",role).issuedAt(new Date()).expiration(new Date(System.currentTimeMillis()+60000)).signWith(Keys.hmacShaKeyFor(key)).compact();return "Bearer "+token;}
}
