%% DESIGN-CLASS17
classDiagram
  class C["SecondhandProductController"] {
    <<controller>>
    +handleRequest()
  }
  class S["SecondhandProductServiceImpl"] {
    <<service>>
    +executeUseCase()
  }
  class P["SecondhandProduct"] {
    <<collaborator>>
    +applyBusinessRule()
  }
  class O["OrderInfo"] {
    <<collaborator>>
    +applyBusinessRule()
  }
  class I["OrderItem"] {
    <<collaborator>>
    +applyBusinessRule()
  }
  C --> S : buySecondhandProduct
  S --> P : 检查 status=ON_SALE 且 buye
  S --> O : create PENDING_PAY
  S --> I : create productType=SECON
